FROM ubuntu

MAINTAINER Masami Yonehara

RUN apt-get update -y
RUN apt-get upgrade -y

# replace PASSWORD
RUN export DEBIAN_FRONTEND=noninteractive
RUN echo mysql-server mysql-server/root_password password eudaimonia | debconf-set-selections
RUN echo mysql-server mysql-server/root_password_again password eudaimonia | debconf-set-selections

RUN apt-get install -y \
  mysql-server \
  mysql-client

EXPOSE 3306
