#!/bin/sh

APP_USER_PASSWORD=app

apt-get update -y
apt-get upgrade -y

apt-get install -y \
  sudo \
  man-db \
  wget \
  git \
  nano \
  curl \
  dialog \
  net-tools \
  patch \
  gcc \
  openssl \
  make \
  bzip2 \
  autoconf \
  automake \
  libtool \
  bison

# add 'app' group and user
addgroup app
useradd app -d /home/app -g app -m -p $APP_USER_PASSWORD
